import type { PatternMeta } from './types'

export const patternList: PatternMeta[] = [
  {
    slug: 'component-composition',
    title: 'Component Composition',
    description: 'Building complex UIs by composing smaller, focused components using children, slots, and the "as" prop pattern.',
    difficulty: 'beginner',
    order: 1,
  },
  {
    slug: 'custom-hooks',
    title: 'Custom Hooks',
    description: 'Extracting reusable stateful logic into custom hooks for sharing across components.',
    difficulty: 'intermediate',
    order: 2,
  },
  {
    slug: 'render-props',
    title: 'Render Props',
    description: 'Sharing code between components using a prop whose value is a function that returns JSX.',
    difficulty: 'intermediate',
    order: 3,
  },
  {
    slug: 'higher-order-components',
    title: 'Higher-Order Components',
    description: 'A function that takes a component and returns a new component with extended behavior.',
    difficulty: 'intermediate',
    order: 4,
  },
  {
    slug: 'compound-components',
    title: 'Compound Components',
    description: 'A set of related components that share implicit state, like Tabs + Tab + TabPanel.',
    difficulty: 'advanced',
    order: 5,
  },
  {
    slug: 'controlled-uncontrolled',
    title: 'Controlled vs Uncontrolled',
    description: 'Understanding when React controls form state vs when the DOM handles it.',
    difficulty: 'intermediate',
    order: 6,
  },
  {
    slug: 'provider-pattern',
    title: 'Provider Pattern',
    description: 'Using React Context to share global state across the component tree without prop drilling.',
    difficulty: 'intermediate',
    order: 7,
  },
  {
    slug: 'container-presentational',
    title: 'Container / Presentational',
    description: 'Separating business logic (container) from rendering (presentational) for cleaner components.',
    difficulty: 'beginner',
    order: 8,
  },
  {
    slug: 'error-boundaries',
    title: 'Error Boundaries',
    description: 'Catching JavaScript errors in the component tree and displaying fallback UIs.',
    difficulty: 'intermediate',
    order: 9,
  },
  {
    slug: 'memoization',
    title: 'Memoization',
    description: 'Optimizing performance with React.memo, useMemo, and useCallback to prevent re-renders.',
    difficulty: 'intermediate',
    order: 10,
  },
  {
    slug: 'portals',
    title: 'Portals',
    description: 'Rendering children into a different DOM subtree outside the parent component hierarchy.',
    difficulty: 'intermediate',
    order: 11,
  },
  {
    slug: 'code-splitting',
    title: 'Code Splitting & Lazy Loading',
    description: 'Splitting bundles and lazily loading components with React.lazy and Suspense.',
    difficulty: 'intermediate',
    order: 12,
  },
  {
    slug: 'state-reducer',
    title: 'State Reducer / Inversion of Control',
    description: 'Allowing consumers to override internal state transitions via a reducer pattern.',
    difficulty: 'advanced',
    order: 13,
  },
  {
    slug: 'props-getters',
    title: 'Props Getters',
    description: 'Providing functions that return prop collections to give consumers full control over rendering.',
    difficulty: 'advanced',
    order: 14,
  },
]
